### ISSUE TITLE
Password strength check

### ISSUE THREAD

**Issue by hemantDwivedi** [hemantDwivedi/password-generator-tool#1]
Should check generated password strength and will show weather password is poor, good, strong, very strong.

**Comment by abant07** [comment]
Hi, I am bit new to Github, but can I take on this issue. Is there anything I should know while I reproduce the environment, or is everything clear in the readme?

Thanks!
Amogh

**Comment by hemantDwivedi** [comment]
Yes, you'll find in readme. fork repo and you can contribute in UI folder. also check my new commit, will help to understand the need.

**Comment by abant07** [comment]
Sounds good!

**Comment by abant07** [comment]
Do you want to have another button called "Generate Password" so the user can set up all the parameters for generating a password(ex: setting the length, having alphabets, special characters). Then the password strength should update accordingly. Also, do you want me to define the boundaries for what is considered a very strong password or is it as simple as saying for each box the user checks off, that maps to how strong the password is. For example, if the user checks all 4 boxes, its a very strong password, if they check 3, its a strong password, if they select 2, its a good password, etc?

Also, just out of curiosity, does the sending password to email work?

**Comment by abant07** [comment]
Also, your copy password doesn't work as well

**Comment by hemantDwivedi** [comment]
Sure, you can add/configure the UI and backend.
