### ISSUE TITLE
Backend for Issue 7

### ISSUE THREAD

**Issue by hemantDwivedi** [hemantDwivedi/password-generator-tool#8]
Check [issue 7](https://github.com/hemantDwivedi/password-generator-tool/issues/7) 

- Add new endpoint, which returns a password.
- Generate a very strong password.

**Comment by giriharan13** [comment]
What about the length of the password that is to be generated? Should it be equal to the length the user currently has in the slide bar or it should be 24(max)?

**Comment by hemantDwivedi** [comment]
> What about the length of the password that is to be generated? Should it be equal to the length the user currently has in the slide bar or it should be 24(max)?

Password length should same as the user selected length, but only if length is greater or equal 12, if It's not generate a random length(12-24) password.

**Comment by hemantDwivedi** [comment]
and let me know, if you are working on this issue or not, so I can assign this to you.

**Comment by giriharan13** [comment]
yea..i'll start working on it soon

**Comment by hemantDwivedi** [comment]
Thank You for contributing to "password-generator-tool". I'm closing this issue. ❤️
